### ISSUE TITLE
Add Example: Coupling pore network to continuum domain

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM-Examples#12]
This example may be useful to many people that are modeling multiscale media, and it should follow our recent JES paper.

**Comment by masoodmoghaddam** [comment]
Hi dear Jeff
Its interesting for me to know more about this example.
Is there some thing more?

**Comment by jgostick** [comment]
I started it be never finished it...sorry.  I will attempt to finish it for you this weekend :-)

**Comment by masoodmoghaddam** [comment]
Thanks Dear Jeff
Your support makes working with OpenPNM more pleasure.
Best regards
Masood

**Comment by jgostick** [comment]
Hi @masoodmoghaddam 
I have converted the example to a Jupyter notebook and  completed it.  You can view it [here]https://github.com/PMEAL/OpenPNM-Examples/blob/master/Simulations/mixed_continuum_and_pore_network.ipynb), but it seems that Github is not rendering the notebooks correctly at the moment. Hopefully this fixes itself.

**Comment by masoodmoghaddam** [comment]
Thanks Dear Jeff
I will Investigate it.
Best regards
Masood
