### ISSUE TITLE
Extend Example for Statoil Import

### ISSUE THREAD

**Issue by Extremys** [PMEAL/OpenPNM-Examples#17]
Hi Team OpenPNM!
I'm newbie in the OpenPNM world, I try to perform Stokes (Pin/Pout) & Diffusion Fickian from the Statoil pore network import file. Is that possible to extend the existing example [Statoil_import.md](https://github.com/PMEAL/OpenPNM-Examples/blob/master/IO_and_Visualization/Statoil_import.md) ?

**Comment by jgostick** [comment]
Do you mean extend it to illustrate how to perform some simulations on it?  Have you looked at the [boundary_conditions](https://github.com/PMEAL/OpenPNM-Examples/blob/master/Simulations/exploring_boundary_conditions.md) example?  It illustrates how to do a fickian diffusion on a cubic network, so the basic procedure it there. 

As I was looking for that link I realized that we don't have a clear list of examples on how to do the different transport calculations.  I don't want to make the statoil example any more complicated, but I think it's a great idea to explicitly add transport examples with pictures and analysis.

**Comment by Extremys** [comment]
Thank you for your quick answer!
Yes, it's exactly that. 
I have consulted this example and others, but I have not tried to perform Fickian Diffusion, only Stokes Simulation but unfortunately it didn't work until now... (The solver said that the matrix was singular...) That's why (I think) maybe more complete examples with statoil file import could help the community.
I don't know if it's the good place to post my problem but I don't find any forum. ;)

**Comment by jgostick** [comment]
Interesting.  Singular matrix means that inlet is not connected to the
outlet.  I'll try running a simulation on it and get back to you.

**Comment by Extremys** [comment]
Thank you for taking some of your time.
I am interested to have the script used, if you reach successfully perform a simulation example!

>  Interesting. Singular matrix means that inlet is not connected to the outlet. I'll try running a simulation on it and get back to you.

**Comment by jgostick** [comment]
Hi @extremys, I have updated the statoil example...it's in PR #21 .

**Comment by Extremys** [comment]
Hi @jgostick, Thank you for your work!
I tried to run the isolated Statoil_import example but I think I'm missing something because when I print calculated Permeability, I get:

```
K from calc_eff_permeability method = nan
K from Darcy Law = [ nan]
OpenPNM version: 1.5
```
(I updated the last Master branch version from OpenPNM repository)
I join the warning output and the corresponding script:

```
import scipy as sp
import OpenPNM as op

import os
path = os.path.join('fixtures', 'ICL-Sandstone(Berea)')
pn = op.Utilities.IO.Statoil.load(path=path, prefix='Berea')
pn.name = 'berea'

op.export_data(network=pn, filename='imported_statoil')

clusters = pn.find_clusters2(mask=pn.Ts >= 0)
pn.trim(pores=clusters > 0)

geom = op.Geometry.GenericGeometry(network=pn, pores=pn.Ps, throats=pn.Ts)
water = op.Phases.Water(network=pn)
phys = op.Physics.GenericPhysics(network=pn, phase=water, geometry=geom)

for item in pn.props():
       if item not in ['throat.conns', 'pore.coords']:
           geom.update({item: pn.pop(item)})

geom['pore.diameter'] = 2*geom['pore.radius']
geom.models.add(propname='pore.area',
                model=op.Geometry.models.pore_area.spherical)
geom['throat.diameter'] = 2*geom['throat.radius']
geom.models.add(propname='throat.area',
                model=op.Geometry.models.throat_area.cylinder)


phys.models.add(propname='throat.hydraulic_conductance',
                model=op.Physics.models.hydraulic_conductance.hagen_poiseuille)


flow = op.Algorithms.StokesFlow(network=pn, phase=water)
flow.set_boundary_conditions(pores=pn.pores('inlets'), bctype='Dirichlet', bcvalue=200000)
flow.set_boundary_conditions(pores=pn.pores('outlets'), bctype='Dirichlet', bcvalue=100000)
flow.run()
flow.return_results()

K = flow.calc_eff_permeability()

print("K from calc_eff_permeability method =",K)

mu = sp.mean(water['pore.viscosity'])
delta_P = 100000
# Using the rate method of the StokesFlow algorithm
Q = sp.absolute(flow.rate(pores=pn.pores('inlets')))
# Because we know the inlets and outlets are at x=0 and x=X
Lx = sp.amax(pn['pore.coords'][:, 0]) - sp.amin(pn['pore.coords'][:, 0])
A = Lx*Lx  # Since the network is cubic Lx = Ly = Lz
K = Q*mu*Lx/(delta_P*A)

print("K from Darcy Law =",K)

print("OpenPNM version:",op.__version__)
```

Some ideas?

[output.err.txt](https://github.com/PMEAL/OpenPNM-Examples/files/521258/output.err.txt)

**Comment by jgostick** [comment]
I think those errors are ok...they just mean that the boundary pores don't lie in a flat plane, so the flux calculation is a bit off (hopefully not too much).  The other errors are corrected with  ```pn.trim(pores=clusters > 0)``` line.

**Comment by Extremys** [comment]
@jgostick Yes I'm totally ok with you, it concerns permeability values. In fact I get "Not a Number" values of permeability in the both case (Darcy law & OpenPNM method).

> K from calc_eff_permeability method = nan
> K from Darcy Law = [ nan]
> OpenPNM version: 1.5

I don't know how to fix the problem, any idea or diagnostic?
I tried with 2 configurations (Ubuntu 14.04 & 16.04) with respectively python 3.4 & 3.5.2 and OpenPNM 1.5 version. I can investigate more.

**Comment by jgostick** [comment]
I"m sorry, I misread your err.txt file.  I just occurred to me that you are probably doing this example on a different data set than the berea data I got from blunts website, right?  If so then there must be a problem with your extracted network.  Can you try to run the example on the sample data found in OpenPNM/test/fixtures/ICL-Sandstone(Berea)?

**Comment by jgostick** [comment]
Ok, never mind, I see from your example that you did use the Berea example network.  Try doing the following:
```
print(pn.check_network_health())
print(geom.check_data_health())
print(water.check_data_health())
print(phys.check_data_health())

```

This should indicate if there are NaNs in any of the property arrays.

**Comment by Extremys** [comment]
Thank you for your help, yes I try to run strictly the same test on berea datas downloaded from this repository. I get NaNs on call `water.check_data_health()` method only:
```
------------------------------------------------------------
pore.temperature          []
pore.thermal_conductivity []
pore.contact_angle        []
pore.critical_pressure    []
pore.molecular_weight     []
pore.surface_tension      []
pore.viscosity            []
pore.molar_density        []
pore.pressure             Has NaNs
pore.diffusivity          []
pore.critical_temperature []
pore.density              []
throat.rate               Has NaNs
pore.vapor_pressure       []
pore.critical_volume      []
------------------------------------------------------------
```

(I join the full output if you need it)
[output.txt](https://github.com/PMEAL/OpenPNM-Examples/files/525354/output.txt)

**Comment by jgostick** [comment]
I have no idea why this worked before but is broken now...anyway, the lines that trim disconnected pores from the network were not working so I've just changed it and pushed to master (bad thing to do, but just easier).  Try now.

**Comment by Extremys** [comment]
Yes that's weird... 
I tried and thanks! It fixed the problem, I found the same values for berea permeability. :)

**Comment by jgostick** [comment]
Awesome!  I'm still not sure why K is different than reported by blunt,
probably he uses the shape factor info? Good luck!

**Comment by Extremys** [comment]
@jgostick  I think so. In this [paper](https://workspace.imperial.ac.uk/earthscienceandengineering/public/external/Research/PERM/Dong%20and%20Blunt%20PRE%202009.pdf), they tell that they use this [code](http://www.imperial.ac.uk/earth-science/research/research-groups/perm/research/pore-scale-modelling/software/two-phase-network-modelling-code/) to calculate absolute permeability on the generated network, but I have not tried to deepen the subject for the moment.

**Comment by firaji2000** [comment]
l have a problem with setting the boundary conditions in Jupyter. l deal with the below error
AttributeError: 'StokesFlow' object has no attribute 'set_boundary_conditions'

**Comment by jgostick** [comment]
We shortened the name to ``set_value_BC`` and ``set_value_BC``.  If you type press tab after adding the '.' to the end of your object name, you'll get a list of available attributes.  You can scroll through the list to go 'shopping' for what you're looking for.

**Comment by firaji2000** [comment]
Hi , Thanks for your quick answers
I starting to work on OpenPNM by its tutorial and its not a new version! what is the new version of the below code :
geom1.models.add(propname='pore.diameter',model=OpenPNM.Geometry.models.pore_diameter.weibull,scale=0.00002, loc=0.000001, seeds='pore.seed')   

and what do you propose me about refrences for deep learning on multi-scale pore network with OpenPNM?
Thank you very much.

**Comment by jgostick** [comment]
Does this help: https://openpnm.readthedocs.io/en/master/getting_started/quick_start.html

**Comment by firaji2000** [comment]
Hi 
I defined 2 networks  with specific geometries for them and I want to stitch them with topotools function  in Openpnm , but I deal with the following error: " Cannot stitch a Network with active objects " . 
Can you help me?
thanks

**Comment by jgostick** [comment]
The problem is that you've created geomertry/phase/phase objects.  When stitching networks, just do it before you do any other actions.  The reason is that we'd have to 'stitch' the other objects as well.  We could technically do it but we haven't implemented it yet.

**Comment by firaji2000** [comment]
Thanks for your quick response
excuse me ,  if we have a networks of pores and throats , how can I determine the connection number(connectivity)  of each pore? Is there a specific function (in OpenPNM ) for this ?

**Comment by jgostick** [comment]
net.num_neighbors(pores=net.Ps)

**Comment by firaji2000** [comment]
Thank a lot 
when I load a network by using " op.io.Statoil.load "  function in openpnm ,  without any trimming , I see that the number of pores(Np) is equal to number in .dat file that I've been extracted before and it's Ok ,  but number of throats(Nt) Is NOT equal( less than)  number that is in .dat file. what is the problem?

**Comment by jgostick** [comment]
The statoil format is a mess.  It includes many throats that connect the sample to the "reservoir" meaning inlet/outlet regions.  We trim those throats, because it's possible to add your own boundary pores.
