### ISSUE TITLE
Fickian Diffusion on Statoil Import

### ISSUE THREAD

**Issue by Extremys** [PMEAL/OpenPNM-Examples#25]
Hi Team OpenPNM!

I try to perform Fickian Diffusion from Statoil import Pore Network (on berea example), but it appears that there is a singularity in the matrix set (similar problem from this previous [issue](https://github.com/PMEAL/OpenPNM-Examples/issues/17) maybe?)... Can you help me? I join the output and the python script.

[diffusionPost.py.txt](https://github.com/PMEAL/OpenPNM-Examples/files/919924/diffusionPost.py.txt)

[output.txt](https://github.com/PMEAL/OpenPNM-Examples/files/919903/output.txt)

**Comment by jgostick** [comment]
Hi @Extremys 
Looking at your supplied text file I see that you've not rn ```pn.check_network_health()``` on the network.  The maximum ball networks tend to have a lot of blind pores, which we call ```disconnected_pores```.  

Basically, just add this after your import: ```pn.trim(pn.check_network_health()['trim_pores'])```

**Comment by Extremys** [comment]
Hi @jgostick, it seems that it works thanks for your super-reactivity!

**Comment by jgostick** [comment]
I just happened to be answering some other question on Github this morning...don't expect this kind of service all the time!  :-)
