### ISSUE TITLE
Can thermal conduction algorithm  be used in pore network? 

### ISSUE THREAD

**Issue by wangkeupc** [PMEAL/OpenPNM-Examples#35]
Dear Dr. @jgostick 
I'm Clark from UPC. The simulation example gives the thermal conduction case. In the case, you built the 2D pore network and set the value of throat length very small. And from your report in the InterPore conference of USA and Qingdao, China, I saw that you simulate thermal conduction in the soild phase. I don't know if the simulation was carried out in the soild phase network and used pore network modelling combined with thermal conduction algorithm?  And in the sphere packing, the sphere particles contact each other. If you don't mind, would you please explain how you deal with the throat diameter and throat length in the soild phase network?
Look forward to you reply. Thanks a lot!

**Comment by jgostick** [comment]
I'm so sorry...I did not notice issue!  I'm guessing that you don't need to know the answer any more, but I'll say a few words anyway.  The 'Dual' solid-pore network simulations are something that we are doing with network extraction...and there is not an example here that shows how to use it.  It is actually more of a PoreSpy thing.  As this is still a new approach, we don't really have any standard example that I can give.  I will close this issue for now, sorry.
