### ISSUE TITLE
Simulate the capillary pressure curve for imbibition cases. 

### ISSUE THREAD

**Issue by deep3214** [PMEAL/OpenPNM-Examples#36]
Dear Dr @jgostick,
 I am new to OpenPNM. Currently, I have learned how to produce a capillary pressure drainage curve. I am sure that the imbibition can be simulated by using OpenPNM as well, but not sure how to achieve it. site and bond ordinary percolation? Would it be possible that you share some examples for the imbibition cases? Many Thanks.

**Comment by TomTranter** [comment]
Hi @deep3214,
A simple imbibition model could be done using ordinary percolation with sites. We're still finalizing our examples for version 2 so follow or star this repo for updates.
Thanks

**Comment by deep3214** [comment]
Thanks for your reply. I also read some papers by you I think (Capillary Hysteresis in Neutrally Wettable Fibrous Media: A Pore Network Study of a Fuel Cell Electrode). In the paper, two criteria are used to calculate the entry pressure and both drainage and imbibition are simulated by using invasion percolation controlled by throat size. I am interested in the criteria by using Washburn equation. As a result, the water retention curve hysteresis is achieved by fitting contact angle hysteresis. I am so curious about how to achieve this in coding. Just swap the defending and invading phase and change contact angle?  how to deal with negative pressure as I can't put the contact angle with a value lower than 90 degree? Would it possible to share your code for the hysteresis cases? Many thanks.

**Comment by haoliguo** [comment]
Any updates on the imbibition example? Really looking forward to that :)

**Comment by TomTranter** [comment]
We have a PR for adding 3 notebooks to explain how to reproduce the results of the paper 
https://github.com/PMEAL/OpenPNM/pull/1286

**Comment by TomTranter** [comment]
We now have examples for percolation here
https://github.com/PMEAL/OpenPNM/tree/master/examples/percolation
