### ISSUE TITLE
Error with conduit_conductance- relative permeability curve

### ISSUE THREAD

**Issue by jdrodriguezcar** [PMEAL/OpenPNM-Examples#38]
Dear Dr @jgostick,
I am new in OpenPNM. I am trying to calculate a relative permeability. 
My code is based in this example: https://github.com/PMEAL/OpenPNM-Examples/blob/master/PaperRecreations/Gostick_JPowerSources(2007).rst
However, when I run my code appears this:
> 
  File "/home/juandasaxo/anaconda3/lib/python3.6/site-packages/openpnm/core/Base.py", line 1015, in interleave_data
    raise KeyError(prop)
KeyError: 'throat.conduit_hydraulic_conductance'

Following is the code section  I think is wrong:

`    mod = op.models.physics.multiphase.conduit_conductance
    phys_water.add_model(model= mod,  propname='throat.conduit_hydraulic_conductance',  throat_conductance='throat.hydraulic_conductance')
    phys_air.add_model(model= op.models.physics.multiphase.conduit_conductance, propname='throat.conduit_hydraulic_conductance', throat_conductance='throat.hydraulic_conductance')

  
    
    Stokes_alg_single_phase_water = op.algorithms.StokesFlow(network=pn, phase=water)
    Stokes_alg_single_phase_air =   op.algorithms.StokesFlow(network=pn, phase=air)
           
    Stokes_alg_multi_phase_water = op.algorithms.StokesFlow(network=pn, phase=water)
    Stokes_alg_multi_phase_air = op.algorithms.StokesFlow(network=pn, phase=air)
    
    
    
    Stokes_alg_single_phase_water.setup(phase = water, conductance='throat.hydraulic_conductance')
    Stokes_alg_single_phase_air.setup(phase = air,conductance='throat.hydraulic_conductance')
    
    Stokes_alg_multi_phase_water.setup(phase = water, conductance='throat.conduit_hydraulic_conductance')
    Stokes_alg_multi_phase_air.setup(phase = air, conductance='throat.conduit_hydraulic_conductance')

`

Thank's for your help.

**Comment by jgostick** [comment]
Can you check the version of OpenPNM you're using by entering op.__version__ at the python console?  The example you link to is for version 1, but you might be using version 2 by the looks of the error you're getting.  If you are using 2, then you should refer to this updated example:

https://github.com/PMEAL/OpenPNM-Examples/blob/update_to_V2/PaperRecreations/Gostick2007.ipynb

If you're not using 2, then you should upgrade to it using ``pip install --upgrade openpnm``, then again refer to the above example.  

This reminds me that we need to move the examples repo over to use V2 now...which I will do soon.

**Comment by jdrodriguezcar** [comment]
Thanks. I have had problems because I was using the first version of OpenPNM due to I only found examples for this version. 

Is it possible to see the irreducible saturations in the relative permeability curve?

Thanks so much for these libraries.

**Comment by jgostick** [comment]
Irreducible saturation only occurs when there is trapping of the defending phase.  The invasion percolation algorithm has an option to apply trapping.  Note that the ordinary percolation based algorithms do not allow trapping...for philosophical reasons.  We currently do not have an example for using IP, but the docstring is quite detailed....you can also look at the tests folder to see how we call and run it for testing purposes.  Sorry I don't have a better answer for you...we're working on the docs and examples but have a few higher priorities right now.

**Comment by jdrodriguezcar** [comment]
The problem was a property that was missing in the geometry. The example helped me to solve this issue but does not run for version 2 of OpenPNM. At least in the computers in which I tried to run.

**Comment by haoliguo** [comment]
The link for the updated example seems not to work... Do we have the right example code for openpnm version 2?

**Comment by jdrodriguezcar** [comment]
@haoliguo I made other modifications to the code and it worked for me, I used the invasion percolation algorithm. However, another OpenPNM user (@ xu-kai-xu) proposed a code and it also worked for me (he used ordinary percolation). Here you can check it: https://github.com/PMEAL/OpenPNM-Examples/pull/56

**Comment by jdrodriguezcar** [comment]
(@haoliguo )

**Comment by haoliguo** [comment]
> @haoliguo I made other modifications to the code and it worked for me, I used the invasion percolation algorithm. However, another OpenPNM user (@xu-kai-xu) proposed a code and it also worked for me (he used ordinary percolation). Here you can check it: #56

@jdrodriguezcar Thank you so much! I followed your instructions and reproduced the plots successfully using OrdinaryPercolation. Are you aware of any examples about imbibition using OrdinaryPercolation? Ultimately I want to conduct imbibition (wetting and invading phase = water, non-wetting and defending phase = oil) after primary drainage (invading phase = oil, defending phase = water). 

Should we just change contact angles in "phase" to indicate which phase is wetting phase and which is non-wetting phase? Say if I set water phase contact angle = 10 and oil phase contact angle = 160, will the openpnm detect that wetting phase = water and non-wetting phase = oil automatically....? 

In my understanding the invading phase (wp: water) should enter smallest throats first (with largest Pc, entry) during imbibition and larger throats (smaller Pc) are entered later. Should we reverse 'filter_pc''s order from Gostick 2007 example to conduct imbibition?

@jgostick @TomTranter @ma-sadeghi @maghighi Could you also help? Many many thanks!

**Comment by xu-kai-xu** [comment]
@jdrodriguezcar , hi, i am very curious about the difference between ordinary and invasion percolation. I have read the famous article about invasion percolation ([David Wilkinson, 1983](https://pdfs.semanticscholar.org/f0d9/ae81ddf3cd3ccb7b8037f7a203cc36463cdb.pdf)), but did not understand the difference between them. Would you please explain it for me? Thanks a lot.

**Comment by TomTranter** [comment]
Ordinary has a set of discrete invasion pressures and finds clusters of pores that are connected by throats that have capillary entry pressure below each threshold in steps of increasing pressure. So if you have invasion pressures [100, 200, 300, ... 10000 ] Pa it will find all the pores connected by throats with entry pressure less than 100 Pa and also connected to an inlet, then it will find new pores connected by throats with entry pressure less than 200 and so on until the final pressure which should exceed all the throat entry pressures in the network and all the pores should be invaded. The number of steps involved equals the number of pressure points you give the algorithm

Invasion starts with a set of inlet pores and invades new ones sequentially choosing the connecting throat with the smallest capillary entry pressure. It essentially produces the same information but the pressure is dynamic. If you run invasion and keep track of the highest pressure that associated with all the invading throats you get a curve similar to ordinary percolation so we sometimes say that ordinary percolation is the envelope to invasion percolation. The number of steps involved equals the number of pores in the network. The behind the scenes accounting is more intensive for invasion but it's the only way to capture certain information and to perform transient simulations properly.

Ordinary percolation is quasi-static and invasion is dynamic.

The code below shows they are the same - for simplicity I have made the throat volume zero

```
import openpnm as op
import numpy as np
import matplotlib.pyplot as plt

net = op.network.Cubic(shape=[100, 100, 1], spacing=2e-5)
geo = op.geometry.StickAndBall(network=net, pores=net.Ps, throats=net.Ts)
geo['throat.volume'] = 0.0
water = op.phases.Water(network=net)
phys = op.physics.Standard(network=net, geometry=geo, phase=water)
OP = op.algorithms.OrdinaryPercolation(network=net, phase=water)
OP.set_inlets(net.pores('back'))
OP.setup(pore_volume='pore.volume',
         throat_volume='throat.volume')
OP.run()
fig = OP.plot_intrusion_curve()

IP = op.algorithms.InvasionPercolation(network=net)
IP.setup(phase=water,
         pore_volume='pore.volume',
         throat_volume='throat.volume')
IP.set_inlets(net.pores('back'))
IP.run()

inv_pressures = np.unique(OP['pore.invasion_pressure'])
IP_sats = []
pvol = net['pore.volume']
totvol = np.sum(pvol)
for Pc in inv_pressures:
    mask = IP['throat.entry_pressure'] > Pc
    if np.any(mask):
        seq = np.min(IP['throat.invasion_sequence'][mask])
        IP_sats.append(np.sum(pvol[IP['pore.invasion_sequence']<seq])/totvol)
    else:
        IP_sats.append(1.0)

plt.plot(inv_pressures, IP_sats)
```

**Comment by jgostick** [comment]
I will also add something that may be relevant to rel-perm calcs:  In the latest dev branch I have altered OP so that the *inlet* pores are NOT set to preinvaded.  This has several upsides:

1.  You do not need to put 0 volume in them to get the Pc curve to start at Snwp = 0, it happens naturally now.
2.  You do not need to artificially tweak the conductances of the inlet pores to get defending phase flowing through them.

The down side is that the inlet pores only become filled IF one of their throats is filled...so this is a bit unnatural or arbitrary.  It seemed like a reasonable trade-off though, given how much confusion this was causing.

**Comment by xu-kai-xu** [comment]
@TomTranter , thank you. The explanation is great. Dose it mean that ordinary percolation starts with one inlet but invasion starts with many inlets? And because the steps of invasion equal to the number of pores, it can model dynamic problems. Is that right?

**Comment by TomTranter** [comment]
This seems like it can be closed now
