### ISSUE TITLE
Get capillary pressure curves when using InvasionPercolation

### ISSUE THREAD

**Issue by deep3214** [PMEAL/OpenPNM-Examples#39]
Dear @jgostick  and @TomTranter,

How are you? I have some questions about the OpenPNM. First of all, I would like to thanks for your contribution to OpenPNM. It is a very useful software for me. 

Here, I am just wondering how to get the capillary pressure curves when I use invasion percolation. It seems that there is no subclass such as plot_primary drainage curves as Ordinary percolation. 

Also, if I want to simulate the hysteresis of the water retention curve. My current approach is to simulate the drainage case by using bond-percolation while to simulate the wetting case by using site percolation (ink bottle effect). How does the drainage case connect to the wetting case ( a full drainage and wetting cycle)? Would it be possible for simulating the scanning curves? 

Appreciate your help to answer my questions. Many thanks

Best Regards,
Zhang

**Comment by TomTranter** [comment]
Hi @deep3214,

InvasionPercolation can return results for a given invading phase saturation. This is a dictionary containing the pore and throat occupancy. These can be used to generate the capillary pressure curve but actually it's a little tricky so apologies for that. The algorithm stores invasion_pressure and you would need to look for the highest value in the pores and throats that are occupied for a given saturation. We could make the function a little more user friendly by passing a pressure to the results function or indeed building a wrapper for it to generate the curve. @jgostick I'm not sure why this wasn't provided. Maybe as InvasionPercolation is supposed to be a very basic implementation that users can customize. MixedInvasionPercolation is more complex with more options and has the ability to generate the curve and also start from a partially filled network so its probably worth you looking at that instead. I am yet to provide an example on how to use it but there are actually lots of smaller examples in our tests that you can look at for now. https://github.com/PMEAL/OpenPNM/blob/master/tests/unit/algorithms/MixedPercolationTest.py

**Comment by deep3214** [comment]
Hi @TomTranter,
Thanks for your response.  I will definitely look into the mixedInvasion Percolation. 
Thanks again for your help. 

Best regards,
Zhang

**Comment by TomTranter** [comment]
We now have examples on percolation here
https://github.com/PMEAL/OpenPNM/tree/master/examples/percolation
