### ISSUE TITLE
Stokes Flow

### ISSUE THREAD

**Issue by Abolfazlmsl** [PMEAL/OpenPNM-Examples#45]
Hello,
I wrote a simple code from IO_and_Visualization section of examples but i received an error.The error is:
KeyError='dq'
I tested stokes flow in another codes but i received same error.How can i fix it?
Thanks for your help.
Best regards,
Abolfazl 

![untitled](https://user-images.githubusercontent.com/41609766/47290452-74a93d00-d60c-11e8-9580-a32499b8a18e.png)

**Comment by jgostick** [comment]
This error is coming from scipy, and seems as though something is not configured correctly.  Do you have umfpack installed?  If you do `pip install umfpack` what happens?

**Comment by jgostick** [comment]
Also, try updating your openpnm with `pip install --upgrade openpnm`

**Comment by Abolfazlmsl** [comment]
Thank you Dr.Gostick
I upgraded my openpnm version and it worked.
