### ISSUE TITLE
Bug in Hydraulic conductance throat.flow_shape_factors

### ISSUE THREAD

**Issue by Saeid-Sli** [PMEAL/OpenPNM-Examples#49]
There is a bug in the calculation of "statoil_import_and_permeability_calculation" example. The new version of "hagen_poiseuille" in OpenPNM version 2.X uses "throat.flow_shape_factor" of "pore1", "pore2", and "throat"for calculation of "hydraulic_conductance" of all throats.

These parameters should be available in "phase" during the calculations. However, the statoil code does not directly import them from the statoil files (Only one "throat.shape_factor" is available in statoil files). Thus, in the misc.py code at lines of 70 to 75 the try-exception structure throws an error. Subsequently, all shape factors are set to 1. 

    try:
        SF1 = phase[conduit_shape_factors+'.pore1'][throats]
        SFt = phase[conduit_shape_factors+'.throat'][throats]
        SF2 = phase[conduit_shape_factors+'.pore2'][throats]
    except KeyError:
        SF1 = SF2 = SFt = 1.0

This results in a big different in the calculation of the permeability of the statoil image from previous version of OpenPNM (K=4756md) to that in the newer version (K=409 md).

**Comment by xu-kai-xu** [comment]
Hi,  I find confusing stuff, "Hydraulic conductance" or "Hydraulic conductivity".
First is, do they mean the same thing in a similar way.
Second is that I find 4 different ways to define it, using a symbol "g":

1.  g_1 = pi*(R^4)/(8*miu)        DOI: 10.1007/s11242-004-5468-2, equation (17);
2.  g_2 = pi*(R^4)/(8*L)            https://doi.org/10.1016/j.fuel.2016.04.078, equation (8);
3.  g_3 = k*(A^2)*G/(miu)         DOI: 10.1007/s11242-004-5468-2, equation (19);
4.  g_4 = pi*(R^4)/(8*miu*L)     DOI: 10.1016/j.jpowsour.2007.04.059, equation(5);

![image](https://user-images.githubusercontent.com/44153643/57835485-2bf7e200-77f1-11e9-8239-4ebe0ff1c487.png)

Thanks.

**Comment by jgostick** [comment]
The calculation of hydraulic conductance is a bit confused, and the definition changes depending where you look.  g1 in your image is the standard way, g2 is not correct, g3 involves shape factors which are used heavily by the Blunt group to adjust their conductance, and g4 is just the hagan-poisseuille equation so is not really a conductance.  The meaning of the word conductance is analogous to Ohm's law, so conductance (g) is the inverse of resistance, (R), thus I = g(V1 - V2).  In terms of fluid flow, it's Q = g(P1 - P2) where Q is flow and P is pressure.  The idea is to group all the scaling factors into a single constant, called g.

**Comment by jgostick** [comment]
this is fixed

**Comment by xu-kai-xu** [comment]
@jgostick  Thanks a lot. BTY, you said "fixed" means that the bug is fixed, right? does that mean we need to update the version?

**Comment by jgostick** [comment]
V2.1 has these fixes incorporated, but it's not on PIP yet....will do it in a day or two

**Comment by xu-kai-xu** [comment]
@jeff good news. please tell me if it is accessible on pip. thanks.
