### ISSUE TITLE
How to print complete data array in openpnm

### ISSUE THREAD

**Issue by xu-kai-xu** [PMEAL/OpenPNM-Examples#55]
Sometimes I need to check the array in openpnm, for example, `sgl['pore.coords']`. But the command `numpy.set_printoptions(threshold='nan')` or `numpy.set_printoptions(threshold=None)` is not useful for pnm objects.  Does anyone know how to realize that?

**Comment by jgostick** [comment]
We don't do anything to overwrite this behavior.  We don't subclass numpy arrays, just store them in the OpenPNM dicts.

I find that these functions work as expected for me.  For instance:

```
>>> pn['pore.coords']
array([[5.0e-05, 5.0e-05, 5.0e-05],
       [5.0e-05, 5.0e-05, 1.5e-04],
       [5.0e-05, 5.0e-05, 2.5e-04],
       ...,
       [9.5e-04, 9.5e-04, 7.5e-04],
       [9.5e-04, 9.5e-04, 8.5e-04],
       [9.5e-04, 9.5e-04, 9.5e-04]])

>>> # Change some options
>>> np.set_printoptions(linewidth=20)
>>> pn['pore.coords']
array([[5.0e-05,
        5.0e-05,
        5.0e-05],
       [5.0e-05,
        5.0e-05,
        1.5e-04],
       [5.0e-05,
        5.0e-05,
        2.5e-04],
       ...,
       [9.5e-04,
        9.5e-04,
        7.5e-04],
       [9.5e-04,
        9.5e-04,
        8.5e-04],
       [9.5e-04,
        9.5e-04,
        9.5e-04]])
```

One of the examples that you give above does not work for me however as 'nan' threshold is not valid.  The None threshold does not throw an error for me but doesn't seem to do anything.

**Comment by xu-kai-xu** [comment]
Sorry to bother you again, maybe I do not clarify my question clear. I just want to print all the data with no omitting.

**Comment by jgostick** [comment]
Ahh, in that case do ``np.set_printoptions(threshold=pn.Np)``  to print ALL the entries in pore.coords
