### ISSUE TITLE
Question about results function in invasion percolation

### ISSUE THREAD

**Issue by deep3214** [PMEAL/OpenPNM-Examples#57]
Dear @jgostick @TomTranter,

Sorry to bother you. 

I am using invasion percolation to simulate the drainage in porous media. 
It seems that the results function (ip.results(Snwp=)) doesn't work after I use ip.apply_trapping(outlets=).
The function of apply_trapping changes the invasion sequence and set the trapped pore/throat to be -1. That may be the reason that the results function doesn't work. 

Could you help me to solve this problem?

Also referring to your paper (pore networking modeling of compressed fuel cell components with OpenPBM), I am just wondering how you analyze the saturation at the breakthrough point (the simulation stopped when the invading phase just occupies one of the pores at the outlet boundary)

Thank you very much. 
Best regards,
Zhang

**Comment by jgostick** [comment]
Hi @deep3214 
We actually have an open issue on the OpenPNM repo about this.  The apply_trapping function sets trapped pores to -1, but leaves the sequence of invasion of non-trapped pores the same.  We are debating whether the invasion sequence should be re-numbered to fill in the missing gaps.  In other words, if the original invasion sequence was [0, 1, 5, 3, 4] it becomes [0, 1, 5, -1, -1] after the trapping is applied.  One could argue that it should probably become [0, 1, 2, -1, -1].  You can then find all pores/throats that are invaded at each sequence using boolean logic (Ps = ip['pore.invasion_sequence'] <= X) and (ip['pore.invasion_sequence'] >= 0).

Regarding breakthough point, this is done by finding the smallest value of invasion sequence among the outlet pores, like `` N = min(ip['pore.invasion_sequence'][ip.pores('outlets')])``.  Then you can use the above logic to find all pores that were invaded at an invasion step of N or less.

**Comment by deep3214** [comment]
@jgostick Thanks for your reply. Your advice helps me a lot. 
I just have one last small question. Would you share some examples of cooperative pore filling? I tried it but it seems not working. Normally, we need to analyze the filling angle when dealing with cooperative pore filling. I am just curious how the filling angle is considered in the pore network method?

**Comment by jgostick** [comment]
I will leave this up to @TomTranter who wrote the cooperative filling algorithm.  There seems to be a situation with some missing examples, so hopefully he can either recover them or cook up some replacements?

**Comment by TomTranter** [comment]
@jgostick they were never merged into the examples repo. Slipped through the net. You might both want to review them. The network is the same one I used for the paper and I added a "future-proof" pickle file with just the data to fixtures. Even so though the coop filling algorithm takes a little while to run and the notebook (part a) looks like it's hanging for a while. Could do a smaller network but it needs to have the right properties. I made PR #1286. The notebooks are under paper recreations. Tranter2017

**Comment by jgostick** [comment]
Yes, adding the notebooks really slows down the testing...that is one reason to have them in a different repo I guess.  Anyway, we'll survive for now.  The examples can for sure be on smaller networks though, which are probably better for illustrating the point. I'll look at the PR.
