### ISSUE TITLE
UPDATING jupyter notebooks with last version OpenPNM

### ISSUE THREAD

**Issue by angelswat** [PMEAL/OpenPNM-Examples#58]
Im so grateful with openpnm and their contribuitors because you have done a great job with this library. Im working on reasearch in porous media by one year and more.

**With the last version of openpnm all jupyter notebooks should be update, because I run the example scripts and I get errors and errors. You have moved all files from the original folders and you have restructured all the library. Its a crazy and I cant work.**

Exm: https://github.com/PMEAL/OpenPNM-Examples/blob/master/Topology/VoronoiFIbers_example.ipynb

Please @TomTranter and @jgostick fix it, and let us continue working with openpnm. Best regards.

**Comment by TomTranter** [comment]
They're in the main repo now.

**Comment by jgostick** [comment]
https://github.com/PMEAL/OpenPNM/tree/master/examples

**Comment by jgostick** [comment]
Now that they're in the main repo, we will be forced to keep them up to date, or else our test suites won't pass!  This was done specifically to prevent the problem you just encountered.
