### ISSUE TITLE
Question about cooperative pore filling

### ISSUE THREAD

**Issue by deep3214** [PMEAL/OpenPNM-Examples#59]
Dear @jgostick @TomTranter 

I am just wondering, is it possible to consider the cooperative pore filling in invasion percolation?
I find a built-in function (setup coop filling) in MixedInvasionPercolation. But it seems not working. Can this function be applied for a non-fibrous porous media?

Thanks for your help.

Best regards,
Zhang

**Comment by TomTranter** [comment]
@jgostick where did the mixed up examples go?

**Comment by TomTranter** [comment]
We now have examples on percolation here
https://github.com/PMEAL/OpenPNM/tree/master/examples/percolation
