### ISSUE TITLE
Error meassage: No module named 'openpnm'

### ISSUE THREAD

**Issue by Ahmedsf2019** [PMEAL/OpenPNM-Examples#61]
I downloaded Anaconda and installed openPNM in Anaconda Prompt:-
C\users\ahmed\pip install openpnm

I start Python 3.4.3 shell

When I write 
>>> import openpnm as op
 I get an error "No module named 'openpnm'

What is the reason?

**Comment by TomTranter** [comment]
it probably didn't install as we only support python 3.6+
