### ISSUE TITLE
Gostick2007 issue with Ts = sgl.find_neighbor_throats(pores=Ps, mode='intersection', flatten=True)

### ISSUE THREAD

**Issue by alexkey79** [PMEAL/OpenPNM-Examples#63]
Dears
I'm testing Gostick2007 as downloaded from GIT.

But it reports this problem:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-10-40e475f91c1b> in <module>
     10 #2 set up geometries
     11 Ps = sgl.pores('*boundary', mode='not')
---> 12 Ts = sgl.find_neighbor_throats(pores=Ps, mode='intersection', flatten=True)
     13 geo = op.geometry.GenericGeometry(network=sgl,pores=Ps,throats=Ts,name='geo')
     14 geo.add_model(propname='pore.seed',

~\AppData\Local\Continuum\anaconda3\lib\site-packages\openpnm\network\GenericNetwork.py in find_neighbor_throats(self, pores, mode, flatten)
    700             am = self.create_adjacency_matrix(fmt='coo', triu=True)
    701             neighbors = topotools.find_neighbor_bonds(sites=pores, logic=mode,
--> 702                                                       am=am, flatten=True)
    703         return neighbors
    704 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\openpnm\topotools\topotools.py in find_neighbor_bonds(sites, im, am, flatten, logic)
    226             neighbors = sp.all(Ps[conns], axis=1)
    227         elif logic in ['and', 'all', 'intersection']:
--> 228             raise Exception('Specified logic is not implemented')
    229         else:
    230             raise Exception('Specified logic is not implemented')

Exception: Specified logic is not implemented

**Comment by jgostick** [comment]
Hi @alexkey79 
The OpenPNM-Examples repo is being phased out for exactly this reason.  Basically, the example you are looking at works on a specific version of OpenPNM, but as we evolve the code, the example grow out of date.  We have actually moved all the examples to the main repo, [here](https://github.com/PMEAL/OpenPNM/tree/master/examples). You will find the same folder structure, with the same gostick recreation, but working.
