### ISSUE TITLE
How to get the figure in paraview such as Tutorial 1 of 3

### ISSUE THREAD

**Issue by crflucifer** [PMEAL/OpenPNM-Examples#64]
I was learning the example following the Tutorial ，
(https://github.com/PMEAL/OpenPNM-Examples/blob/master/Tutorials/getting_started.ipynb)
but I can not get the figure in paraview such as Tutorial 1 of 3,
My figure only can show the network of pores and throats, but the  The connection in the web has been displayed incorrectly;
I want show the diameter of the pores and throats, and the pressure in the pore by color of the pore like the Tutorial 1 of 3;

**Comment by jgostick** [comment]
https://openpnm.readthedocs.io/en/master/getting_started/visualize_in_paraview.html
