### ISSUE TITLE
How to definition a key to save the information/proprety of every pore and throat such as 'pore.diamete‘ in geometry

### ISSUE THREAD

**Issue by crflucifer** [PMEAL/OpenPNM-Examples#66]
I want to add a proprety/value of  every pore in the geometry or netwrok；
and the proprety need to be displayed such as pore.diamete or pore.pressure

**Comment by TomTranter** [comment]
just add it like a dictionary geometry['pore.my_prop'] = 1.0 will put a 1.0 in every pore or geometry['pore.my_prop'] = numpy.random.random(network.num_pores()) will put different numbers in every pore. This examples repository is getting phased out and we have a bunch of example notebooks over on the main repository. If you are new to python you may have got the code via pip and this can hide the folder away in your python distributions site packages folder. If you open up a terminal and import openpnm the type openpnm.__file__ you get the directory that the code is in. then there should be an examples folder. Please have a look at all of them
