### ISSUE TITLE
water configuration in membrane electrode assembly

### ISSUE THREAD

**Issue by siz23** [PMEAL/OpenPNM-Examples#67]
Dear @jgostick @TomTranter,

I would appreciate if you could help on my questions about water configuration in membrane electrode assembly. 

Currently, my reference is Dr. Gostick's paper (Simulation of a full fuel cell membrane electrode assembly using pore network modeling). I couldn't figure out the part of breakthrough via invasion sequence. I tried to use apply_trapping function but it seems does not work as well. Probably I misunderstand something. Would you please provide some advice on this? For your information, I have attached my script here.

Also, would you please give some advice on placement of the water for simulation of overall cell, as I have a dry run file but do not know how to implement the water configuration into it?

Thanks so much for your help!

Best,

Siming Zhang

**Comment by siz23** [comment]
Sorry, I forgot uploading the file, here it is.

[water_simple_1st.txt](https://github.com/PMEAL/OpenPNM-Examples/files/4130001/water_simple_1st.txt)

**Comment by TomTranter** [comment]
Hi @siz23 the script you sent had a typo in it on line 55
mm.misc.from_neighbor_pores
should be
mm.from_neighbor_pores.
It doesn't sound like that was your problem though. Breakthrough refers to the invading fluid reaching an outlet. You haven't defined any in your simulation.
We're phasing out this repository actually and some percolation examples were recently added to the main OpenPNM repository here We now have examples on percolation here
https://github.com/PMEAL/OpenPNM/tree/master/examples/percolation
I'd suggest looking at the invasion_percolation example there.
